# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_timestamp', models.DateTimeField()),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_id', models.CharField(max_length=100)),
                ('capabilities_url', models.CharField(max_length=100)),
                ('room_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('oauth_secret', models.CharField(max_length=100)),
                ('authorization_url', models.URLField(blank=True)),
                ('token_url', models.URLField(blank=True)),
                ('api_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Installation'),
        ),
    ]
