# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='room_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='room_url',
            field=models.URLField(blank=True),
        ),
    ]
