# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170325_0540'),
        ('core', '0004_auto_20170325_0452'),
    ]

    operations = [
    ]
