# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170325_0806'),
        ('core', '0005_merge_20170325_0906'),
    ]

    operations = [
    ]
