# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=30)),
                ('text', models.TextField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Installation')),
            ],
        ),
    ]
