# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='keyword',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
