# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('answers', '0002_auto_20170324_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='keyword',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('installation', 'keyword')]),
        ),
    ]
